import "fonts/Kameron-Bold.ttf";
import { Theme } from "theme.slint";

export component ClockWindow inherits FocusScope {
    in property <int> clock;
    width: 240px;
    height: 240px;
    Rectangle {
        z: 0;
        background: #029dcc;
        border-radius: 13px;
        width: 20px;
        height: 100px;
        x: 190px;
    }
    HorizontalLayout {
        alignment: center;
        y: 45px;
        Text {
            text: floor(root.clock/3600) + "\n" +floor(root.clock/60);
            color: Theme.text-color;
            font-size: 60px;
        }
        Text {
            y: 30px;
            text: "19\n07";
            color: Theme.text-color;
            font-size: 30px;
        }
    }
}