import "fonts/Kameron-Bold.ttf";
import { ClockWindow } from "clock.slint";
import { Theme } from "theme.slint";
import { AppSelection } from "selector.slint";
import { Settings } from "settings.slint";

export component MainWindow inherits Window {
    width: 240px;
    height: 240px;
    background: Theme.window-background;
    in property <int> clock;
    in property <int> battery;

    public function set-menu(is_open: bool) {
        if (is_open) {
            apps.visible = true;
            clockWindow.visible = false;
            apps.focus();
        } else {
            clockWindow.visible = true;
            apps.visible = false;
            clockWindow.focus();
        }
    }

    clockWindow := ClockWindow {
        visible: false;
        clock: clock;
        battery: battery;
    }

    apps := AppSelection {
        visible: false;
    }
}