import "fonts/Kameron-Bold.ttf";
import { ClockWindow } from "clock.slint";
import { Carousel } from "carousel.slint";
import { Card } from "card.slint";
import { Theme } from "theme.slint";
import { AppSelection } from "selector.slint";

export component MainWindow inherits Window {
    width: 240px;
    height: 240px;
    background: #181818;
    in property <bool> is_main_menu_open;
    in property <int> clock;
    
    if(is_main_menu_open == false) : ClockWindow{clock: clock;}
    if(is_main_menu_open == true) : FocusScope{
        AppSelection {}
    }
}