// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Carousel } from "carousel.slint";
import { Card } from "card.slint";
import { Theme } from "theme.slint";

export component AppSelection inherits FocusScope {
    private property<[{ title: string, image: image}]> navigation-items: [
        { title: "Home", image: @image-url("svg/home_black.svg") },
        { title: "Settings", image: @image-url("svg/settings_black.svg") },
        { title: "About", image: @image-url("svg/info_black.svg") },
        { title: "Home", image: @image-url("svg/home_black.svg") },
        { title: "Home", image: @image-url("svg/home_black.svg") },
    ];
    property <int> selected-index: 2;
    in property <KeyEvent> event;
    width: 240px;
    height: 240px;
    padding: Theme.spacing-regular;
    forward-focus: carousel;

    carousel := Carousel {
        y: (root.width - self.width) / 2;
        height: 100%;
        itemHeight: 35px;
        count: root.navigation-items.length;
        selected-index <=> root.selected-index;
        spacing: 15px;

        for item[index] in root.navigation-items : Card {
            is-selected: index == root.selected-index;
            title: item.title;
            image-source: item.image;
            x: (parent.width - self.width) / 2;

            clicked => { root.selected-index = index; }
        }
    }
}
