import "fonts/Poppins-Regular.ttf";
import "fonts/Poppins-Italic.ttf";
import "fonts/Poppins-Medium.ttf";
import "fonts/Poppins-Light.ttf";

export global Theme  {
    //brushes
    out property <brush> text-color: #f1f3fe;
    out property <brush> background: #020512;
    out property <brush> foreground: #112ab6;
    out property <brush> secondary: #060f41;
    out property <brush> accent: #2846eb;
    //size
    out property <length> size-small: 24px;
    out property <length> size-medium: 128px;
    out property <length> size-big: 170px;
    //animation duration
    out property <duration> duration-regular: 250ms;
    out property <duration> duration-fast: 100ms;
    //radius
    out property <length> radius-regular: 16px;
    //spacing
    out property <length> spacing-regular: 4px;
    out property <length> spacing-medium: 8px;
    // typo
    out property <string> font-family: "Poppins";
    out property <length> font-size-regular: 12px;
    out property <length> font-size-medium: 28px;
    out property <int> font-weight-regular: 400;
    out property <int> font-weight-bold: 900;
}