name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        ldproxy: false
        version: "1.66.0"
        
    - name: Build
      run: cargo build --verbose
